# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b7aba26c312b2d0884da2be43f5b5e7b4ad43ace93978d8e91c6d544c1c0a0849b37c093748c625c7417e681172f3457601cfc08c323bf551cbadb22be2940d

test:
  secret_key_base: b95f390650d3cff5298ceda339891460e3f400be3ac5e438d8f2ce5485049cea0d815b5e1ad83dd75ca941d3933e9ffd8c8aa1c77351a434515f9c03f5355452

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
